### ISSUE TITLE
Concurrency Tests and Thread-Safety

### ISSUE THREAD

**Issue by Firionus** [cueglow/glowdtf#29]
## TODO

- [x] Patch Thread Safety
  - [x] Test Immutability of Maps returned by Getters
  - [x] Create kinda reliable concurrent tests
  - [x] Make tests pass by locking
  - [x] refactor tests for readability and clarity
- [x] SubscriptionHandler Thread Safety
- [ ] ~~Client-Server-based Tests~~
- [x] Document Locking Strategy and Locking Orders
- [x] check TODOs
