### ISSUE TITLE
GDTF handling

### ISSUE THREAD

**Issue by Firionus** [cueglow/glowdtf#5]
## TODO

- [x] Implement HTTP POST endpoint for uploading GDTF file from webui
- [x] parse uploaded GDTF into object via JAXB
- [x] Extract DMX modes with corresponding channel count, Fixture Name and Manufacturer and FixtureTypeId from GDTF object
- [x] How to make these properties available in patch stream?
- [x] Ensure FixtureTypes in ˋPatchˋ cannot be modified from outside
- [x] Make documentation of auto-generated GDTF classes English instead of German
- [x] Test upload of GDTF with client mock 
- [x] Allow deletion of FixtureType
- [x] Check remaining TODOs (ignore TODOs related to streams or other things that will be handled in later PRs)
